"Code: Verilator":
  - changed-files:
      - any-glob-to-any-file: "verilator/**"

"Code: Verilog Support":
  - changed-files:
      - any-glob-to-any-file: "language-support/verilog/**"
      - any-glob-to-any-file: "language-support/verilog-macro/**"
      - any-glob-to-any-file: "language-support/verilog-macro-builder/**"

"Code: Spade Support":
  - changed-files:
      - any-glob-to-any-file: "language-support/spade/"
      - any-glob-to-any-file: "language-support/spade-macro/**"

"Code: Veryl Support":
  - changed-files:
      - any-glob-to-any-file: "language-support/veryl/"
      - any-glob-to-any-file: "language-support/veryl-macro/**"

"Infra: CI":
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/*"
      - any-glob-to-any-file: ".github/labels.yaml"
      - any-glob-to-any-file: ".github/release-please-config.json"

"Documentation":
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
      - any-glob-to-any-file: "assets/**"
