[book]
authors = ["Ethan Uppal"]
language = "en"
multilingual = false
src = "book"
title = "Marlin Handbook"

[build]
build-dir = "docs"

[output.html]
additional-js = ["book/js/verilog-highlight.js", "book/js/spade-highlight.js"]

[preprocessor.callouts] # https://github.com/ToolmanP/rs-mdbook-callouts
