[workspace]
resolver = "2"
members = [
    "verilator",
    "language-support/verilog",
    "language-support/verilog-macro",
    "language-support/verilog-macro-builder",
    "language-support/spade",
    "language-support/spade-macro",
    "language-support/veryl",
    "language-support/veryl-macro",
    "tooling/swim-marlin",
    "examples/verilog-project",
    "examples/spade-project",
    "marlin",
    "language-support/veryl-macro", "examples/veryl_project/example-veryl-project",
]

[workspace.package]
version = "0.1.0"
authors = ["Ethan Uppal"]
edition = "2021"
rust-version = "1.83"
description = "🦀 No nonsense hardware testing in Rust 🛠️"
repository = "https://github.com/ethanuppal/marlin"
readme = "README.md"
license = "MPL-2.0"

[workspace.dependencies]
snafu = "0.8.5"
camino = "1.1.9"
libc = "0.2.169"
libloading = "0.8.6"
proc-macro2 = "1.0.93"
syn = { version = "2.0.96", features = ["full"] }
quote = "1.0.38"
sv-parser = "0.13.3"
spade-parser = "0.12.1"
spade-ast = "0.12.1"
log = "0.4.25"
colog = "1.3.0"
argh = "0.1.13"
toml = "0.8.20"
indicatif = "0.17.11"
owo-colors = "4.1.0"
threadpool = "1.8.1"

marlin-verilator = { path = "verilator", version = "0.1.0" }
marlin-verilog = { path = "language-support/verilog", version = "0.1.0" }
marlin-verilog-macro = { path = "language-support/verilog-macro", version = "0.1.0" }
marlin-verilog-macro-builder = { path = "language-support/verilog-macro-builder", version = "0.1.0" }
marlin-spade = { path = "language-support/spade", version = "0.1.0" }
marlin-spade-macro = { path = "language-support/spade-macro", version = "0.1.0" }
marlin-veryl = { path = "language-support/veryl", version = "0.1.0" }
marlin-veryl-macro = { path = "language-support/veryl-macro", version = "0.1.0" }
