[graph]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
all-features = true

[bans]
multiple-versions = "deny"
wildcards = "deny" # todo: use Veryl crates.io dependency
skip = [
  { crate = "hashbrown@0.14.5", reason = "dashmap@6.1.0 uses this old version" },
  { crate = "syn@1.0.109", reason = "sv-parser-parser@0.13.3 uses this old version" },
  # recomment once veryl is readded as a crates.io dependency
  # { crate = "unicode-width@0.1.14", reason = "veryl-parser@0.14.1 uses this old version" },
  # { crate = "thiserror-impl@1.0.69", reason = "veryl-parser@0.14.1 uses this old version" },
  # { crate = "thiserror@1.0.69", reason = "veryl-parser@0.14.1 uses this old version" },
]
# allow = [
#   { crate = "snafu", reason = "Implements ergonomic error handling and error report printing. I should be able to replace this with my own error handling system." },
#   { crate = "camino", reason = "Complete replacement for native path API but supporting UTF-8. This would be too much effort to rewrite myself and implement all the methods that camino does to make this a drop-in replacement everywhere." },
#   { crate = "libc", reason = "The canonical source for C types, needed when generating bindings from C to Rust" },
#   { crate = "libloading", reason = "The canonical dlopen solution with built-in safety" },
#   { crate = "log", reason = "Standard Rust logging crate" },
#   { crate = "env_logger", reason = "Logger backend with minimal dependencies. Can probably remove and replace with my own logging backend." },
#   { crate = "toml", reason = "Compliant TOML parser" },
#   { crate = "owo-colors", reason = "Zero-dependency terminal colors" },
#   { crate = "glob", reason = "Expands Unix glob patterns. I could probably write this myself with some effort." },
#   { crate = "file-guard", reason = "Interprocess locking" },
#   { crate = "dashmap", reason = "Fast concurrent `HashMap` for interthread locking" },
#
#   { crate = "proc-macro2", reason = "Allows using proc macro types outside of `[lib] proc-macro = true` crates." },
#   { crate = "syn", reason = "Implements a full Rust parser" },
#   { crate = "quote", reason = "Works with syn and proc-macro2 to generate token streams." },
#
#   { crate = "sv-parser", reason = "Fully-compliant SystemVerilog parsers are extremely complicated" },
#   { crate = "spade-parser", reason = "It would not be worth writing another Spade parser beyond the official one" },
#   { crate = "spade-ast", reason = "Need to interact with the Spade AST" },
#
#
#   { crate = "marlin", reason = "Listed as a workspace dependency" },
#   { crate = "marlin-spade", reason = "Listed as a workspace dependency" },
#   { crate = "marlin-spade-macro", reason = "Listed as a workspace dependency" },
#   { crate = "marlin-verilator", reason = "Listed as a workspace dependency" },
#   { crate = "marlin-verilog", reason = "Listed as a workspace dependency" },
#   { crate = "marlin-verilog-macro", reason = "Listed as a workspace dependency" },
#   { crate = "marlin-verilog-macro-builder", reason = "Listed as a workspace dependency" },
#
#   { crate = "aho-corasick@1.1.3", reason = "Pulled in by a dependency" },
#   { crate = "autocfg@1.4.0", reason = "Pulled in by a dependency" },
#   { crate = "beef@0.5.2", reason = "Pulled in by a dependency" },
#   { crate = "bytecount@0.6.8", reason = "Pulled in by a dependency" },
#   { crate = "cfg-if@1.0.0", reason = "Pulled in by a dependency" },
#   { crate = "colored@3.0.0", reason = "Pulled in by a dependency" },
#   { crate = "crossbeam-utils@0.8.21", reason = "Pulled in by a dependency" },
#   { crate = "either@1.14.0", reason = "Pulled in by a dependency" },
#   { crate = "equivalent@1.0.2", reason = "Pulled in by a dependency" },
#   { crate = "fnv@1.0.7", reason = "Pulled in by a dependency" },
#   { crate = "hashbrown@0.15.2", reason = "Pulled in by a dependency" },
#   { crate = "heck@0.5.0", reason = "Pulled in by a dependency" },
#   { crate = "indexmap@2.7.1", reason = "Pulled in by a dependency" },
#   { crate = "itertools@0.14.0", reason = "Pulled in by a dependency" },
#   { crate = "lazy_static@1.5.0", reason = "Pulled in by a dependency" },
#   { crate = "local-impl@0.1.2", reason = "Pulled in by a dependency" },
#   { crate = "lock_api@0.4.12", reason = "Pulled in by a dependency" },
#   { crate = "logos@0.15.0", reason = "Pulled in by a dependency" },
#   { crate = "logos-codegen@0.15.0", reason = "Pulled in by a dependency" },
#   { crate = "logos-derive@0.15.0", reason = "Pulled in by a dependency" },
#   { crate = "memchr@2.7.4", reason = "Pulled in by a dependency" },
#   { crate = "minimal-lexical@0.2.1", reason = "Pulled in by a dependency" },
#   { crate = "nom@7.1.3", reason = "Pulled in by a dependency" },
#   { crate = "nom-greedyerror@0.5.0", reason = "Pulled in by a dependency" },
#   { crate = "nom-packrat@0.7.0", reason = "Pulled in by a dependency" },
#   { crate = "nom-packrat-macros@0.7.0", reason = "Pulled in by a dependency" },
#   { crate = "nom-recursive@0.5.1", reason = "Pulled in by a dependency" },
#   { crate = "nom-recursive-macros@0.5.1", reason = "Pulled in by a dependency" },
#   { crate = "nom-tracable@0.9.1", reason = "Pulled in by a dependency" },
#   { crate = "nom-tracable-macros@0.9.1", reason = "Pulled in by a dependency" },
#   { crate = "nom_locate@4.2.0", reason = "Pulled in by a dependency" },
#   { crate = "num@0.4.3", reason = "Pulled in by a dependency" },
#   { crate = "num-bigint@0.4.6", reason = "Pulled in by a dependency" },
#   { crate = "num-complex@0.4.6", reason = "Pulled in by a dependency" },
#   { crate = "num-integer@0.1.46", reason = "Pulled in by a dependency" },
#   { crate = "num-iter@0.1.45", reason = "Pulled in by a dependency" },
#   { crate = "num-rational@0.4.2", reason = "Pulled in by a dependency" },
#   { crate = "num-traits@0.2.19", reason = "Pulled in by a dependency" },
#   { crate = "once_cell@1.20.3", reason = "Pulled in by a dependency" },
#   { crate = "parking_lot_core@0.9.10", reason = "Pulled in by a dependency" },
#   { crate = "pin-project-lite@0.2.16", reason = "Pulled in by a dependency" },
#   { crate = "regex@1.11.1", reason = "Pulled in by a dependency" },
#   { crate = "regex-automata@0.4.9", reason = "Pulled in by a dependency" },
#   { crate = "regex-syntax@0.8.5", reason = "Pulled in by a dependency" },
#   { crate = "rustc_version@0.4.1", reason = "Pulled in by a dependency" },
#   { crate = "same-file@1.0.6", reason = "Pulled in by a dependency" },
#   { crate = "scopeguard@1.2.0", reason = "Pulled in by a dependency" },
#   { crate = "semver@1.0.25", reason = "Pulled in by a dependency" },
#   { crate = "serde@1.0.218", reason = "Pulled in by a dependency" },
#   { crate = "serde_derive@1.0.218", reason = "Pulled in by a dependency" },
#   { crate = "serde_spanned@0.6.8", reason = "Pulled in by a dependency" },
#   { crate = "smallvec@1.14.0", reason = "Pulled in by a dependency" },
#   { crate = "snafu-derive@0.8.5", reason = "Pulled in by a dependency" },
#   { crate = "spade-codespan@0.12.0", reason = "Pulled in by a dependency" },
#   { crate = "spade-codespan-reporting@0.12.0", reason = "Pulled in by a dependency" },
#   { crate = "spade-common@0.13.0", reason = "Pulled in by a dependency" },
#   { crate = "spade-diagnostics@0.13.0", reason = "Pulled in by a dependency" },
#   { crate = "spade-macros@0.13.0", reason = "Pulled in by a dependency" },
#   { crate = "str-concat@0.2.0", reason = "Pulled in by a dependency" },
#   { crate = "sv-parser-error@0.13.3", reason = "Pulled in by a dependency" },
#   { crate = "sv-parser-macros@0.13.3", reason = "Pulled in by a dependency" },
#   { crate = "sv-parser-parser@0.13.3", reason = "Pulled in by a dependency" },
#   { crate = "sv-parser-pp@0.13.3", reason = "Pulled in by a dependency" },
#   { crate = "sv-parser-syntaxtree@0.13.3", reason = "Pulled in by a dependency" },
#   { crate = "termcolor@1.4.1", reason = "Pulled in by a dependency" },
#   { crate = "thiserror@1.0.69", reason = "Pulled in by a dependency" },
#   { crate = "thiserror-impl@1.0.69", reason = "Pulled in by a dependency" },
#   { crate = "toml_datetime@0.6.8", reason = "Pulled in by a dependency" },
#   { crate = "toml_edit@0.22.24", reason = "Pulled in by a dependency" },
#   { crate = "tracing@0.1.41", reason = "Pulled in by a dependency" },
#   { crate = "tracing-attributes@0.1.28", reason = "Pulled in by a dependency" },
#   { crate = "tracing-core@0.1.33", reason = "Pulled in by a dependency" },
#   { crate = "unicode-ident@1.0.17", reason = "Pulled in by a dependency" },
#   { crate = "unicode-width@0.2.0", reason = "Pulled in by a dependency" },
#   { crate = "walkdir@2.5.0", reason = "Pulled in by a dependency" },
#   { crate = "winapi@0.3.9", reason = "Pulled in by a dependency" },
#   { crate = "winapi-util@0.1.9", reason = "Pulled in by a dependency" },
#   { crate = "windows-sys@0.59.0", reason = "Pulled in by a dependency" },
#   { crate = "windows-targets@0.52.6", reason = "Pulled in by a dependency" },
#   { crate = "windows_x86_64_gnu@0.52.6", reason = "Pulled in by a dependency" },
#   { crate = "windows_x86_64_msvc@0.52.6", reason = "Pulled in by a dependency" },
# ]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"

[sources.allow-org]
github = ["veryl-lang"]

[licenses]
allow = ["MIT", "Apache-2.0", "MPL-2.0", "EUPL-1.2", "ISC", "Unicode-3.0"]
confidence-threshold = 1.0
