[package]
name = "marlin-verilator-stable"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
libloading.workspace = true
snafu.workspace = true
