[package]
name = "marlin-builder"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
boxcar.workspace = true
libloading.workspace = true
marlin-verilator-stable.workspace = true
