name: Docs

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - name: Install mdbook
        uses: peaceiris/actions-mdbook@v2.0.0
        with:
          mdbook-version: "0.4.37"
      - name: Install callouts preprocessor
        run: cargo install --locked --git https://github.com/ToolmanP/rs-mdbook-callouts --rev 83898e352a961fc65044e04c864141c8b5481722
      - name: Build
        run: mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
